#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbICBF")]
	public partial class ORMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAsistencia(Asistencia instance);
    partial void UpdateAsistencia(Asistencia instance);
    partial void DeleteAsistencia(Asistencia instance);
    partial void InsertAvanceAcademico(AvanceAcademico instance);
    partial void UpdateAvanceAcademico(AvanceAcademico instance);
    partial void DeleteAvanceAcademico(AvanceAcademico instance);
    partial void InsertJardin(Jardin instance);
    partial void UpdateJardin(Jardin instance);
    partial void DeleteJardin(Jardin instance);
    partial void InsertPersonas(Personas instance);
    partial void UpdatePersonas(Personas instance);
    partial void DeletePersonas(Personas instance);
    partial void InsertRol(Rol instance);
    partial void UpdateRol(Rol instance);
    partial void DeleteRol(Rol instance);
    #endregion
		
		public ORMDataContext() : 
				base(global::Modelo.Properties.Settings.Default.dbICBFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ORMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Asistencia> Asistencia
		{
			get
			{
				return this.GetTable<Asistencia>();
			}
		}
		
		public System.Data.Linq.Table<AvanceAcademico> AvanceAcademico
		{
			get
			{
				return this.GetTable<AvanceAcademico>();
			}
		}
		
		public System.Data.Linq.Table<Jardin> Jardin
		{
			get
			{
				return this.GetTable<Jardin>();
			}
		}
		
		public System.Data.Linq.Table<NinoAsistencia> NinoAsistencia
		{
			get
			{
				return this.GetTable<NinoAsistencia>();
			}
		}
		
		public System.Data.Linq.Table<Personas> Personas
		{
			get
			{
				return this.GetTable<Personas>();
			}
		}
		
		public System.Data.Linq.Table<Rol> Rol
		{
			get
			{
				return this.GetTable<Rol>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_login")]
		public ISingleResult<sp_loginResult> sp_login([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string clave)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correo, clave);
			return ((ISingleResult<sp_loginResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asistencia")]
	public partial class Asistencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<int> _codMadre;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OncodMadreChanging(System.Nullable<int> value);
    partial void OncodMadreChanged();
    #endregion
		
		public Asistencia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codMadre", DbType="Int")]
		public System.Nullable<int> codMadre
		{
			get
			{
				return this._codMadre;
			}
			set
			{
				if ((this._codMadre != value))
				{
					this.OncodMadreChanging(value);
					this.SendPropertyChanging();
					this._codMadre = value;
					this.SendPropertyChanged("codMadre");
					this.OncodMadreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AvanceAcademico")]
	public partial class AvanceAcademico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _codNino;
		
		private System.Nullable<System.DateTime> _anoEscolar;
		
		private string _nivel;
		
		private string _notas;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fechaEntregaNota;
		
		private EntityRef<Personas> _Personas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncodNinoChanging(System.Nullable<int> value);
    partial void OncodNinoChanged();
    partial void OnanoEscolarChanging(System.Nullable<System.DateTime> value);
    partial void OnanoEscolarChanged();
    partial void OnnivelChanging(string value);
    partial void OnnivelChanged();
    partial void OnnotasChanging(string value);
    partial void OnnotasChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaEntregaNotaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaEntregaNotaChanged();
    #endregion
		
		public AvanceAcademico()
		{
			this._Personas = default(EntityRef<Personas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codNino", DbType="Int")]
		public System.Nullable<int> codNino
		{
			get
			{
				return this._codNino;
			}
			set
			{
				if ((this._codNino != value))
				{
					if (this._Personas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodNinoChanging(value);
					this.SendPropertyChanging();
					this._codNino = value;
					this.SendPropertyChanged("codNino");
					this.OncodNinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anoEscolar", DbType="Date")]
		public System.Nullable<System.DateTime> anoEscolar
		{
			get
			{
				return this._anoEscolar;
			}
			set
			{
				if ((this._anoEscolar != value))
				{
					this.OnanoEscolarChanging(value);
					this.SendPropertyChanging();
					this._anoEscolar = value;
					this.SendPropertyChanged("anoEscolar");
					this.OnanoEscolarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel", DbType="VarChar(200)")]
		public string nivel
		{
			get
			{
				return this._nivel;
			}
			set
			{
				if ((this._nivel != value))
				{
					this.OnnivelChanging(value);
					this.SendPropertyChanging();
					this._nivel = value;
					this.SendPropertyChanged("nivel");
					this.OnnivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notas", DbType="VarChar(200)")]
		public string notas
		{
			get
			{
				return this._notas;
			}
			set
			{
				if ((this._notas != value))
				{
					this.OnnotasChanging(value);
					this.SendPropertyChanging();
					this._notas = value;
					this.SendPropertyChanged("notas");
					this.OnnotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaEntregaNota", DbType="Date")]
		public System.Nullable<System.DateTime> fechaEntregaNota
		{
			get
			{
				return this._fechaEntregaNota;
			}
			set
			{
				if ((this._fechaEntregaNota != value))
				{
					this.OnfechaEntregaNotaChanging(value);
					this.SendPropertyChanging();
					this._fechaEntregaNota = value;
					this.SendPropertyChanged("fechaEntregaNota");
					this.OnfechaEntregaNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personas_AvanceAcademico", Storage="_Personas", ThisKey="codNino", OtherKey="id", IsForeignKey=true)]
		public Personas Personas
		{
			get
			{
				return this._Personas.Entity;
			}
			set
			{
				Personas previousValue = this._Personas.Entity;
				if (((previousValue != value) 
							|| (this._Personas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Personas.Entity = null;
						previousValue.AvanceAcademico.Remove(this);
					}
					this._Personas.Entity = value;
					if ((value != null))
					{
						value.AvanceAcademico.Add(this);
						this._codNino = value.id;
					}
					else
					{
						this._codNino = default(Nullable<int>);
					}
					this.SendPropertyChanged("Personas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Jardin")]
	public partial class Jardin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombreJardin;
		
		private string _direccion;
		
		private string _telefono;
		
		private string _estado;
		
		private EntitySet<Personas> _Personas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreJardinChanging(string value);
    partial void OnnombreJardinChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    #endregion
		
		public Jardin()
		{
			this._Personas = new EntitySet<Personas>(new Action<Personas>(this.attach_Personas), new Action<Personas>(this.detach_Personas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreJardin", DbType="VarChar(200)")]
		public string nombreJardin
		{
			get
			{
				return this._nombreJardin;
			}
			set
			{
				if ((this._nombreJardin != value))
				{
					this.OnnombreJardinChanging(value);
					this.SendPropertyChanging();
					this._nombreJardin = value;
					this.SendPropertyChanged("nombreJardin");
					this.OnnombreJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(200)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(200)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(200)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jardin_Personas", Storage="_Personas", ThisKey="id", OtherKey="codJardin")]
		public EntitySet<Personas> Personas
		{
			get
			{
				return this._Personas;
			}
			set
			{
				this._Personas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Personas(Personas entity)
		{
			this.SendPropertyChanging();
			entity.Jardin = this;
		}
		
		private void detach_Personas(Personas entity)
		{
			this.SendPropertyChanging();
			entity.Jardin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NinoAsistencia")]
	public partial class NinoAsistencia
	{
		
		private int _idAsistencia;
		
		private int _idNino;
		
		private string _estadoNino;
		
		private System.Nullable<System.DateTime> _hora;
		
		public NinoAsistencia()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAsistencia", DbType="Int NOT NULL")]
		public int idAsistencia
		{
			get
			{
				return this._idAsistencia;
			}
			set
			{
				if ((this._idAsistencia != value))
				{
					this._idAsistencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNino", DbType="Int NOT NULL")]
		public int idNino
		{
			get
			{
				return this._idNino;
			}
			set
			{
				if ((this._idNino != value))
				{
					this._idNino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadoNino", DbType="VarChar(200)")]
		public string estadoNino
		{
			get
			{
				return this._estadoNino;
			}
			set
			{
				if ((this._estadoNino != value))
				{
					this._estadoNino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="DateTime")]
		public System.Nullable<System.DateTime> hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this._hora = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personas")]
	public partial class Personas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _tipoRol;
		
		private System.Nullable<int> _numeroIdentificacion;
		
		private string _nombres;
		
		private string _apellidos;
		
		private System.Nullable<System.DateTime> _fechaNacimiento;
		
		private string _ciudadNacimiento;
		
		private string _tipoSangre;
		
		private System.Nullable<int> _codAcudiente;
		
		private string _telefono;
		
		private string _celular;
		
		private string _direccion;
		
		private string _eps;
		
		private string _peso;
		
		private string _talla;
		
		private string _correo;
		
		private string _clave;
		
		private System.Nullable<int> _codJardin;
		
		private EntitySet<AvanceAcademico> _AvanceAcademico;
		
		private EntitySet<Personas> _Personas2;
		
		private EntityRef<Jardin> _Jardin;
		
		private EntityRef<Personas> _Personas1;
		
		private EntityRef<Rol> _Rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntipoRolChanging(System.Nullable<int> value);
    partial void OntipoRolChanged();
    partial void OnnumeroIdentificacionChanging(System.Nullable<int> value);
    partial void OnnumeroIdentificacionChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OnfechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaNacimientoChanged();
    partial void OnciudadNacimientoChanging(string value);
    partial void OnciudadNacimientoChanged();
    partial void OntipoSangreChanging(string value);
    partial void OntipoSangreChanged();
    partial void OncodAcudienteChanging(System.Nullable<int> value);
    partial void OncodAcudienteChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnepsChanging(string value);
    partial void OnepsChanged();
    partial void OnpesoChanging(string value);
    partial void OnpesoChanged();
    partial void OntallaChanging(string value);
    partial void OntallaChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OncodJardinChanging(System.Nullable<int> value);
    partial void OncodJardinChanged();
    #endregion
		
		public Personas()
		{
			this._AvanceAcademico = new EntitySet<AvanceAcademico>(new Action<AvanceAcademico>(this.attach_AvanceAcademico), new Action<AvanceAcademico>(this.detach_AvanceAcademico));
			this._Personas2 = new EntitySet<Personas>(new Action<Personas>(this.attach_Personas2), new Action<Personas>(this.detach_Personas2));
			this._Jardin = default(EntityRef<Jardin>);
			this._Personas1 = default(EntityRef<Personas>);
			this._Rol = default(EntityRef<Rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoRol", DbType="Int")]
		public System.Nullable<int> tipoRol
		{
			get
			{
				return this._tipoRol;
			}
			set
			{
				if ((this._tipoRol != value))
				{
					if (this._Rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntipoRolChanging(value);
					this.SendPropertyChanging();
					this._tipoRol = value;
					this.SendPropertyChanged("tipoRol");
					this.OntipoRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroIdentificacion", DbType="Int")]
		public System.Nullable<int> numeroIdentificacion
		{
			get
			{
				return this._numeroIdentificacion;
			}
			set
			{
				if ((this._numeroIdentificacion != value))
				{
					this.OnnumeroIdentificacionChanging(value);
					this.SendPropertyChanging();
					this._numeroIdentificacion = value;
					this.SendPropertyChanged("numeroIdentificacion");
					this.OnnumeroIdentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(200)")]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(200)")]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this.OnfechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._fechaNacimiento = value;
					this.SendPropertyChanged("fechaNacimiento");
					this.OnfechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudadNacimiento", DbType="VarChar(200)")]
		public string ciudadNacimiento
		{
			get
			{
				return this._ciudadNacimiento;
			}
			set
			{
				if ((this._ciudadNacimiento != value))
				{
					this.OnciudadNacimientoChanging(value);
					this.SendPropertyChanging();
					this._ciudadNacimiento = value;
					this.SendPropertyChanged("ciudadNacimiento");
					this.OnciudadNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoSangre", DbType="VarChar(200)")]
		public string tipoSangre
		{
			get
			{
				return this._tipoSangre;
			}
			set
			{
				if ((this._tipoSangre != value))
				{
					this.OntipoSangreChanging(value);
					this.SendPropertyChanging();
					this._tipoSangre = value;
					this.SendPropertyChanged("tipoSangre");
					this.OntipoSangreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codAcudiente", DbType="Int")]
		public System.Nullable<int> codAcudiente
		{
			get
			{
				return this._codAcudiente;
			}
			set
			{
				if ((this._codAcudiente != value))
				{
					if (this._Personas1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodAcudienteChanging(value);
					this.SendPropertyChanging();
					this._codAcudiente = value;
					this.SendPropertyChanged("codAcudiente");
					this.OncodAcudienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(200)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(200)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(200)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eps", DbType="VarChar(200)")]
		public string eps
		{
			get
			{
				return this._eps;
			}
			set
			{
				if ((this._eps != value))
				{
					this.OnepsChanging(value);
					this.SendPropertyChanging();
					this._eps = value;
					this.SendPropertyChanged("eps");
					this.OnepsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="VarChar(200)")]
		public string peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this.OnpesoChanging(value);
					this.SendPropertyChanging();
					this._peso = value;
					this.SendPropertyChanged("peso");
					this.OnpesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_talla", DbType="VarChar(200)")]
		public string talla
		{
			get
			{
				return this._talla;
			}
			set
			{
				if ((this._talla != value))
				{
					this.OntallaChanging(value);
					this.SendPropertyChanging();
					this._talla = value;
					this.SendPropertyChanged("talla");
					this.OntallaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(200)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(200)")]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codJardin", DbType="Int")]
		public System.Nullable<int> codJardin
		{
			get
			{
				return this._codJardin;
			}
			set
			{
				if ((this._codJardin != value))
				{
					if (this._Jardin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodJardinChanging(value);
					this.SendPropertyChanging();
					this._codJardin = value;
					this.SendPropertyChanged("codJardin");
					this.OncodJardinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personas_AvanceAcademico", Storage="_AvanceAcademico", ThisKey="id", OtherKey="codNino")]
		public EntitySet<AvanceAcademico> AvanceAcademico
		{
			get
			{
				return this._AvanceAcademico;
			}
			set
			{
				this._AvanceAcademico.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personas_Personas", Storage="_Personas2", ThisKey="id", OtherKey="codAcudiente")]
		public EntitySet<Personas> Personas2
		{
			get
			{
				return this._Personas2;
			}
			set
			{
				this._Personas2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jardin_Personas", Storage="_Jardin", ThisKey="codJardin", OtherKey="id", IsForeignKey=true)]
		public Jardin Jardin
		{
			get
			{
				return this._Jardin.Entity;
			}
			set
			{
				Jardin previousValue = this._Jardin.Entity;
				if (((previousValue != value) 
							|| (this._Jardin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Jardin.Entity = null;
						previousValue.Personas.Remove(this);
					}
					this._Jardin.Entity = value;
					if ((value != null))
					{
						value.Personas.Add(this);
						this._codJardin = value.id;
					}
					else
					{
						this._codJardin = default(Nullable<int>);
					}
					this.SendPropertyChanged("Jardin");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Personas_Personas", Storage="_Personas1", ThisKey="codAcudiente", OtherKey="id", IsForeignKey=true)]
		public Personas Personas1
		{
			get
			{
				return this._Personas1.Entity;
			}
			set
			{
				Personas previousValue = this._Personas1.Entity;
				if (((previousValue != value) 
							|| (this._Personas1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Personas1.Entity = null;
						previousValue.Personas2.Remove(this);
					}
					this._Personas1.Entity = value;
					if ((value != null))
					{
						value.Personas2.Add(this);
						this._codAcudiente = value.id;
					}
					else
					{
						this._codAcudiente = default(Nullable<int>);
					}
					this.SendPropertyChanged("Personas1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Personas", Storage="_Rol", ThisKey="tipoRol", OtherKey="id", IsForeignKey=true)]
		public Rol Rol
		{
			get
			{
				return this._Rol.Entity;
			}
			set
			{
				Rol previousValue = this._Rol.Entity;
				if (((previousValue != value) 
							|| (this._Rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Rol.Entity = null;
						previousValue.Personas.Remove(this);
					}
					this._Rol.Entity = value;
					if ((value != null))
					{
						value.Personas.Add(this);
						this._tipoRol = value.id;
					}
					else
					{
						this._tipoRol = default(Nullable<int>);
					}
					this.SendPropertyChanged("Rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AvanceAcademico(AvanceAcademico entity)
		{
			this.SendPropertyChanging();
			entity.Personas = this;
		}
		
		private void detach_AvanceAcademico(AvanceAcademico entity)
		{
			this.SendPropertyChanging();
			entity.Personas = null;
		}
		
		private void attach_Personas2(Personas entity)
		{
			this.SendPropertyChanging();
			entity.Personas1 = this;
		}
		
		private void detach_Personas2(Personas entity)
		{
			this.SendPropertyChanging();
			entity.Personas1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rol")]
	public partial class Rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private EntitySet<Personas> _Personas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public Rol()
		{
			this._Personas = new EntitySet<Personas>(new Action<Personas>(this.attach_Personas), new Action<Personas>(this.detach_Personas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(200)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rol_Personas", Storage="_Personas", ThisKey="id", OtherKey="tipoRol")]
		public EntitySet<Personas> Personas
		{
			get
			{
				return this._Personas;
			}
			set
			{
				this._Personas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Personas(Personas entity)
		{
			this.SendPropertyChanging();
			entity.Rol = this;
		}
		
		private void detach_Personas(Personas entity)
		{
			this.SendPropertyChanging();
			entity.Rol = null;
		}
	}
	
	public partial class sp_loginResult
	{
		
		private int _id;
		
		private System.Nullable<int> _tipoRol;
		
		private System.Nullable<int> _numeroIdentificacion;
		
		private string _nombres;
		
		private string _apellidos;
		
		private System.Nullable<System.DateTime> _fechaNacimiento;
		
		private string _ciudadNacimiento;
		
		private string _tipoSangre;
		
		private System.Nullable<int> _codAcudiente;
		
		private string _telefono;
		
		private string _celular;
		
		private string _direccion;
		
		private string _eps;
		
		private string _peso;
		
		private string _talla;
		
		private string _correo;
		
		private string _clave;
		
		private System.Nullable<int> _codJardin;
		
		public sp_loginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoRol", DbType="Int")]
		public System.Nullable<int> tipoRol
		{
			get
			{
				return this._tipoRol;
			}
			set
			{
				if ((this._tipoRol != value))
				{
					this._tipoRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroIdentificacion", DbType="Int")]
		public System.Nullable<int> numeroIdentificacion
		{
			get
			{
				return this._numeroIdentificacion;
			}
			set
			{
				if ((this._numeroIdentificacion != value))
				{
					this._numeroIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(200)")]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this._nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(200)")]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this._apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this._fechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudadNacimiento", DbType="VarChar(200)")]
		public string ciudadNacimiento
		{
			get
			{
				return this._ciudadNacimiento;
			}
			set
			{
				if ((this._ciudadNacimiento != value))
				{
					this._ciudadNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoSangre", DbType="VarChar(200)")]
		public string tipoSangre
		{
			get
			{
				return this._tipoSangre;
			}
			set
			{
				if ((this._tipoSangre != value))
				{
					this._tipoSangre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codAcudiente", DbType="Int")]
		public System.Nullable<int> codAcudiente
		{
			get
			{
				return this._codAcudiente;
			}
			set
			{
				if ((this._codAcudiente != value))
				{
					this._codAcudiente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(200)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(200)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this._celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(200)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eps", DbType="VarChar(200)")]
		public string eps
		{
			get
			{
				return this._eps;
			}
			set
			{
				if ((this._eps != value))
				{
					this._eps = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="VarChar(200)")]
		public string peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_talla", DbType="VarChar(200)")]
		public string talla
		{
			get
			{
				return this._talla;
			}
			set
			{
				if ((this._talla != value))
				{
					this._talla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(200)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(200)")]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this._clave = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codJardin", DbType="Int")]
		public System.Nullable<int> codJardin
		{
			get
			{
				return this._codJardin;
			}
			set
			{
				if ((this._codJardin != value))
				{
					this._codJardin = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
